
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;


/**
 *
 * @author kgonz
 */
public class CodeDuplicateDetector extends javax.swing.JFrame {

    boolean buttonClicked = false;
    String fileData = "";
    /**
     * Creates new form CodeDuplicateDetector
     */
    public CodeDuplicateDetector() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        button1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        button2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Code Duplication Detector");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Please submit a file.");
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        button1.setBackground(new java.awt.Color(236, 236, 253));
        button1.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        button1.setText("Submit Files");
        button1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 255), new java.awt.Color(153, 153, 255)), javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255))));

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 204, 255), new java.awt.Color(153, 153, 255)), javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255))));
        jTextArea2.setSelectionColor(new java.awt.Color(204, 204, 255));
        jScrollPane2.setViewportView(jTextArea2);

        button2.setBackground(new java.awt.Color(229, 229, 255));
        button2.setText("Scan for Duplication");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button2)
                .addGap(393, 393, 393))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button2)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
                
        if (evt.getSource()==button1)
        {
            JFileChooser submit_file = new JFileChooser();
            
           int response = submit_file.showOpenDialog(null);
           // int responseSave = submit_file.showSaveDialog(null);
           
           if(response == JFileChooser.APPROVE_OPTION)
           {
               File path = new File(submit_file.getSelectedFile().getAbsolutePath());
               
        FileReader fr = null; 
                try {
                    fr = new FileReader(path);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(CodeDuplicateDetector.class.getName()).log(Level.SEVERE, null, ex);
                }
        
      //  String fileData = "";
        
        int c; 
                try {
                    while((c=fr.read()) != -1) 
                        fileData += (char)c;
                } catch (IOException ex) {
                    Logger.getLogger(CodeDuplicateDetector.class.getName()).log(Level.SEVERE, null, ex);
                }
               System.out.println("Opening source file from the path-> "+path);
               System.out.println(fileData);
    
               
               jLabel1.setText("File submitted!");
               jLabel2.setText("Opening  " + path);
               jTextArea2.setText(fileData);
           }

           buttonClicked = true;
        }
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        
                if (evt.getSource()==button2 && buttonClicked == false )
        {
            jTextArea2.setText("   Please choose a file first! ");
        }
        
        if (evt.getSource()==button2 && buttonClicked == true )
        {
          //  jTextArea2.setText("yoo");
            
            
String[] elements = fileData.split("[;\\r\\n\"]");


// step two : convert String array to list of String
List<String> fixedLenghtList = Arrays.asList(elements);

// step three : copy fixed list to an ArrayList
ArrayList<String> listOfDuplicates = new ArrayList<String>(fixedLenghtList);

//listOfDuplicates = listOfDuplicates.replaceAll("\n", " ");

listOfDuplicates.removeIf(s -> s.contains("}"));
listOfDuplicates.removeIf(s -> s.contains("{"));
listOfDuplicates.removeIf(s -> s.contains("/**"));
listOfDuplicates.removeIf(s -> s.contains("*/"));
listOfDuplicates.removeIf(s -> s.contains("/*"));
listOfDuplicates.removeIf(s -> s.contains("]"));
listOfDuplicates.removeIf(s -> s.contains("["));
listOfDuplicates.removeIf(s -> s.contains("license"));
listOfDuplicates.removeIf(s -> s.contains("@"));
listOfDuplicates.removeIf(s -> s.contains("\\s"));

listOfDuplicates.remove(" ");

ArrayList<String> listOfDuplicatesCopy = new ArrayList<String>(fixedLenghtList);

int dupCount = 0;

for (int i = 0; i < listOfDuplicates.size()-1; i++) 
{
   // String itemI = listOfDuplicates.get(i);
  for (int j = i+1; j < listOfDuplicates.size(); j++) 
  {
     // String itemJ = listOfDuplicates.get(j);
      // listOfDuplicates.get(i) == listOfDuplicates.get(j)
      //listOfDuplicates.get(i).contains(listOfDuplicates.get(j))
    if (listOfDuplicates.get(i) == listOfDuplicates.get(j)) 
    {
        System.out.println("Duplicate string: " + listOfDuplicates.get(i) + "and " + listOfDuplicates.get(j) );
        
        listOfDuplicatesCopy.add(listOfDuplicates.get(i));
        listOfDuplicatesCopy.add(listOfDuplicates.get(j));
        dupCount ++;
  }
    
}}

int sizeCount = listOfDuplicates.size() ;
int TotalDupl = sizeCount / dupCount;



System.out.println("DupeCount: " + dupCount + "\n The duplicate code found is: " +listOfDuplicatesCopy +
        "\nThe total duplicate code found is " + TotalDupl + " or %" + TotalDupl*100);

System.out.println("list from comma separated String : " + listOfDuplicates);

System.out.println("size of ArrayList : " + listOfDuplicates.size());
// jTextArea2.setText("The tokens : " + listOfDuplicates);
    }//GEN-LAST:event_button2ActionPerformed
    }
    
    
    private void stringDuplicatePercent()
    {
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CodeDuplicateDetector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CodeDuplicateDetector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CodeDuplicateDetector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CodeDuplicateDetector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CodeDuplicateDetector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
